### PR TITLE
Update buttonmap.xml and topology.xml

### PR DESCRIPTION
**Pull request by garbear**
## Description

This PR updates buttonmap.xml and topology.xml.

### buttonmap.xml

Changes to buttonmap.xml:
* Fix gamepad subclass
* Add additional subclasses (commented as they don't have profiles yet)

### topology.xml

Change to topology.xml:
* Flattened topology

## How has this been tested?

Tested in Nestopia on the game Gauntlet II. All four controllers can control players.

### CODE REVIEW

**Comment by KOPRajs** [comment]
@garbear I'm not sure if this is the best approach (to force the multitap all the time). It is probably going to work for Nestopia, because it doesn't distinguish between a controller connected directly to port 1 and a controller connected through the multitap, but it is not meant like this by design. Also this is probably not going to work for every emulator (it won't work for _Genesis GX Plus_).

I'd rather stay with the flat topology design here (as we did for other emulators, which don't support proper topology yet, e.g. like the PCSX, Picodrive etc.). It would be more consistent approach and also it is the way the Nestopia really works (it actually has 4 primary ports), so why try to hide it from users?

**Comment by garbear** [comment]
> It is probably going to work for Nestopia

This PR is the first time I've suggested this approach, I'm not suggesting we apply it to any other emulator.

> so why try to hide it from users?

My idea is the opposite, instead of hiding the fact that the NES has two ports (the user shouldn't know about the underlying Nestopia), we show that 4 ports are possible because a multitap (that can't be interacted with) is in use.

So the two options:

* Show four controllers without a multitap
* Show four controllers with a multitap that can't be interacted with

I think the second is more honest as to how the original console worked, and the emulator sees the same regardless because the multitap uses `connectionPort="-1"`.

> it is the way the Nestopia really works

We should do it the way the console really works, as emulation and emulators should be hidden.

> it doesn't distinguish between a controller connected directly to port 1 and a controller connected through the multitap

That's actually the genius of this approach - it lets us be more faithful to the hardware and the emulator doesn't care. Because the multitap uses `connectionPort="-1"`, it's never assigned a libretro port, and depth-first will guarantee the emulator always sees controllers as ports 1-4 regardless if they are connected via multitap or direct console ports.

> why?

My final argument is "because we can for free". Either way the user sees four controllers, but an XML change we add a NES 4 Score to both the controller dialog, so its description is visible, and the port dialog, so the vintage "wiring" is more visible and less abstracted to suit an emulator.

The XML is also a more accurate representation of the truth. The game is: describe the data accurately, then make it look pretty in the UI. So if you think the multitap should be hidden, then we should still include it in the XML but in the GUI flatten a single multitap.

Also, in addition to the "because we can" argument, a more complex topology lets us catch bugs. I've already discovered some missing checks when resetting a port list with a multitap.

**Comment by garbear** [comment]
OK, I played with this for a while, trying to fix the bugs that would allow for a multitap, and ultimately it needs information from a player manager. Given that we don't have one, I'm removing the multitap and replacing it with four controllers.

**Comment by garbear** [comment]
At least we came away with a bug fix: https://github.com/xbmc/xbmc/pull/22836

**Comment by KOPRajs** [comment]
I'm sorry to hear that you've been forced to change the approach this way.

I look at the matter from a different perspective. Users don't care about multitaps or the real hardware wiring. They just need the simplest way to get working controls. The multitaps add complexity to the port setup, but we need them for the more complex emulators, because the emulator itself doesn't recognize whether the game supports multitap or not, so it is up to the user to decide the topology of the connected controllers for a specific game. But if it is not necessary in this case, then lets not add complexity and also don't add the multitap as a dependency for this emulator.

**Comment by garbear** [comment]
Have you seen the latest state? Does this look good? It doesn't use multitaps.

**Comment by KOPRajs** [comment]
> Have you seen the latest state? Does this look good? It doesn't use multitaps.

Yes, I've seen it. Looks good indeed.

**Pull request merged**
