### PR TITLE
Renames

### PR DESCRIPTION
**Pull request by notspiff**
- Rename to game.libretro.nestopia
- Switch extension point (companion pr: https://github.com/garbear/xbmc/pull/24)

### CODE REVIEW

**Comment by garbear** [comment]
K, gonna start the night off with the rebrand

**Comment by garbear** [comment]
@notspiff we got a shitload of addons to port over. can i give you access to kodi-game organization?

**Comment by notspiff** [comment]
you certainly can. i need a list of which are wanted though. and i only do linux.

**Comment by garbear** [comment]
certainly all the ones https://github.com/notspiff?tab=repositories. aside from that, go crazy

**Comment by notspiff** [comment]
all of those done and _compile tested_ on linux amd64. exception is the mednafen ones, upstream split the repo and i cba to redo that right now, i can already feel my brain having shrunk from doing the 20 others.

**Comment by garbear** [comment]
nice. input is now the last thing between us and playable games. i'm hoping to have the keyboard working by the end of the week.

to standardize controllers between different emus, i started making controller add-ons like this: https://github.com/kodi-game/kodi-game-peripherals/blob/master/addons/game.controller.snes/layout.xml.

i'd like to standardize platforms as well. I've [tried this once](https://github.com/garbear/xbmc/commit/8fafa85#diff-26ed13d615a85ae88cd22ffc19e291cbR47) already, but this data really needs to not be in c++. can you think of a better way?

**Comment by notspiff** [comment]
the controller addons seems fine to me, they map from a console to a generic controller. then you map the generic controller to a particular system in the peripheral addon.

the map of platform maps from console to file extensions. i'd make a resource addon for an xml with the info, then fill a std::map<std::string, PlatformInfo> from that xml file. you then rely on strings from addon.xml for the game addons, with some generic fallback for nonexistent systems.

or did i not get your question?

**Comment by garbear** [comment]
i woke up to 20 stupid github new repo subscription notifications. never been so pleased to get spammed in my life ;)

I'll check out resource add-ons. I was thinking maybe adding adding `xbmc.game.system` extension point, and having each system extend this, but I don't think we should ship 80 separate add-ons for all the systems.

As this std::map should to be exposed to scrapers and scripts, I was also thinking of ignoring platforms and letting scrapers handle this. I've already completed the game extension list for topfs2's python scraper, https://github.com/topfs2/heimdall/blob/master/src/game_item.py#L87

**Comment by notspiff** [comment]
you said go wild ;)

you should ask the community to help provide the metadata and such, addon.xml is mostly placeholders.

**Comment by notspiff** [comment]
oh, and this whole thing caught the github robot detectors attention. i had to prove my humanity to the github staff ;)

**Comment by garbear** [comment]
lmao. you fool no one ;)

**Comment by garbear** [comment]
almost got keyboard input working. trying to finish up by april 1 (arbitrary, yet doable). once my test builds make a big splash on the forum, i'll point ppl over here

**Comment by garbear** [comment]
btw my old hacky libretro build system (a bunch of python, c++ and shell literally held together by dark magic) might have more up-to-date settings.xmls and addon.xmls. https://github.com/garbear/repository.libretro/tree/master/release

**Comment by wsnipex** [comment]
@notspiff heh, I was about to write you a mail asking what happened to your repos :)

**Pull request merged**
