### PR TITLE
turn nestopia into a proper dependency

### PR DESCRIPTION
**Pull request by Montellese**
Needs https://github.com/garbear/xbmc/pull/36 to work properly.

### CODE REVIEW

**Comment by garbear** [comment]
@Montellese @wsnipex @notspiff, you guys are my go-to build system experts, and I have another question for you :)

The command `find_package(nestopia REQUIRED)` doesn't work when building standalone (via the traditional `cd build && cmake ..`)

Here's the error I get:

```
$ cd build && cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/kodi
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "Findnestopia.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "nestopia",
  but CMake did not find one.

  Could not find a package configuration file provided by "nestopia" with any
  of the following names:

    nestopiaConfig.cmake
    nestopia-config.cmake

  Add the installation prefix of "nestopia" to CMAKE_PREFIX_PATH or set
  "nestopia_DIR" to a directory containing one of the above files.  If
  "nestopia" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
```

when building in-tree, it can find the dependency ok. why do you think it can't find nestopia with a standalone build?

**Comment by wsnipex** [comment]
As the error says, there is no Findnestopia.cmake anywhere in your tree. I have no idea how this should work when building in tree. Only reason would be nestopia providing a nestopia-config.cmake file.(I didn't check if it does)

**Comment by Montellese** [comment]
@wsnipex: Our dependency integration of nestopia writes a `nestopia-config.cmake`, see https://github.com/kodi-game/game.libretro.nestopia/pull/4/files#diff-ab8f7fd0a968d2c3d8462999aa22b2c6R44 but maybe it's installing into the wrong path. It works fine on WIN32 but as we saw often in the past that doesn't mean anything for Linux.

**Comment by wsnipex** [comment]
ok.
This nestopia-config.cmake doesn't exist if you build netstopia standalone.
Remember that standalone builds do not use our built-in depends handling, so the config is not generated.

**Comment by wsnipex** [comment]
had a brief look at nestopias build sys: plain Makefile, no pkgconfig :/
best bet is to add a Findnestopia here that simply does find_library(NESTOPIA_LIB nestopia-libretro)

**Comment by a1rwulf** [comment]
I'm afraid this is true for all the libretro build things.

**Comment by Montellese** [comment]
If we add a `Findnestopia.cmake` we should remove the creation of `nestopia-config.cmake` in `depends/common/nestopia/CMakeLists.txt`.

**Comment by garbear** [comment]
so where should a `Findnestopia.cmake` go and how should it look?

**Comment by wsnipex** [comment]
in your addon src root. Assuming the nestopia lib is called nestopia-libretro.[so|dll|dylib]
this might already suffice as content:
find_library(NESTOPIA_LIB nestopia-libretro)

**Comment by garbear** [comment]
Fixed the error, but it seems it can't find the library. I tried both `nestopia-libretro` (the output of the Makefile is named `nestopia-libretro.so`) and `game.libretro.nestopia` (the Makefile output is renamed to `game.libretro.nestopia.so` when installed)

```
$ make
$ make install
Install the project...
-- Install configuration: "Debug"
-- Installing: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia
-- Up-to-date: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/buttonmap.xml
-- Up-to-date: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/addon.xml
-- Installing: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/resources
-- Installing: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/resources/language
-- Installing: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/resources/language/English
-- Up-to-date: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/resources/language/English/strings.po
-- Up-to-date: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/resources/settings.xml
-- Up-to-date: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/changelog.txt
-- Up-to-date: /home/garrett/workspace/xbmc/addons/.//game.libretro.nestopia/icon.png
CMake Error at cmake_install.cmake:40 (FILE):
  file INSTALL cannot find
  "/home/garrett/Documents/game.libretro.nestopia/NESTOPIA_LIB-NOTFOUND".
```

When I build in-tree using `make -C target/binary-addons PREFIX=$HOME/kodi ADDONS="game.libretro.nestopia"` it works correctly:

```
Install the project...
-- Installing: /home/garrett/kodi/lib/kodi/addons/game.libretro.nestopia/game.libretro.nestopia.so
```

In the main `CMakeLists.txt`, the cmake for copying the Makefile output to the install directory is:

``` cmake
find_package(nestopia REQUIRED)
set(DEPLIBS nestopia)
set(NESTOPIA_CUSTOM_BINARY ${NESTOPIA_LIB} game.libretro.nestopia${CMAKE_SHARED_LIBRARY_SUFFIX} nestopia)
build_addon(game.libretro.nestopia NESTOPIA DEPLIBS)
```

**Comment by Montellese** [comment]
The problem is that for standalone you also need to take care of all needed dependencies yourself which in this case means you need to compile nestopia yourself outside of our cmake buildsystem for binary addons.

**Comment by garbear** [comment]
ok, then i guess building standalone isn't an option. I'll stick to building using the strategies in [Readme.md](https://github.com/kodi-game/game.libretro.nestopia/blob/master/Readme.md)

**Comment by wsnipex** [comment]
if you ever want those addons packaged for the PPA, standalone building must work.

**Comment by garbear** [comment]
would reverting this PR do the trick? then nestopia would go back to being build as the main add-on

**Comment by Montellese** [comment]
If you'd revert the whole PR it could work with standalone (can't say for sure) but you'd loose WIN32 building with MinGW again.

**Comment by wsnipex** [comment]
don't revert it, just add the Findnestopia.cmake. Building nestopia manually once, shouldn't really be too hard..

**Pull request merged**
